# Generated by Django 2.2.6 on 2019-10-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('badge_number', models.IntegerField()),
                ('rating', models.FloatField()),
                ('dept', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'officers',
            },
        ),
    ]
