# Generated by Django 2.2.6 on 2019-10-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officers',
            fields=[
                ('badge', models.IntegerField(blank=True, null=True)),
                ('first', models.CharField(blank=True, max_length=64, null=True)),
                ('last', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('stars', models.FloatField(blank=True, null=True)),
                ('profileid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'officers',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
